export let products = [
  {
    id: 1,
    title: "Vagoneta 15kg Perros",
    price: 7200,
    stock: 6,
    description: "Comidas Vivaz para perros adultos de 15kgs.",
    category: "Alimentos",
    img: "https://i.postimg.cc/jDtYKWSB/vagonetaperros.jpg",
  },
  {
    id: 2,
    title: "Vagoneta 20kg Gatos",
    price: 6000,
    stock: 4,
    description: "Comidas Vivaz para gatos adultos de 20kgs.",
    category: "Alimentos",
    img: "https://i.postimg.cc/NKDq0gyF/vagonetagatos.jpg",
  },
  {
    id: 3,
    title: "Anticonceptivos para perros",
    price: 1500,
    stock: 3,
    description: "Pastillas anticonceptivas para perros, 10u",
    category: "Medicación",
    img: "https://i.postimg.cc/dZCcQrdc/anticonceptivos.jpg",
  },
  {
    id: 4,
    title: "Anticonceptivos para gatos",
    price: 1600,
    stock: 2,
    description: "Pastillas anticonceptivas para gatos, 10u",
    category: "Medicación",
    img: "https://i.postimg.cc/dZCcQrdc/anticonceptivos.jpg",
  },
  {
    id: 5,
    title: "Pipeta para gatos medianos",
    price: 2500,
    stock: 7,
    description: "Pipeta para gatos medianos de 2 a 4 kg.",
    category: "Higiene",
    img: "https://i.postimg.cc/SJWbwLkW/pipetagato.jpg",
  },
  {
    id: 6,
    title: "Pipeta para perros medianos",
    price: 3400,
    stock: 6,
    description: "Pipeta para perros medianos de 10 a 20 kg.",
    category: "Higiene",
    img: "https://i.postimg.cc/2Vpfc9Rk/pipetaperro.jpg",
  },
];
